# References:
#
# https://blog.argoproj.io/draft-argo-cd-v2-6-release-candidate-ced1853bbfdb
# https://github.com/argoproj/argo-cd/issues/2531
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
    - resources-finalizer.argocd.argoproj.io
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/projects/
  project: default
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/
  sources:
  - repoURL: https://zabbix-community.github.io/helm-zabbix
    chart: zabbix
    targetRevision: 7.0.6
    helm:
      valueFiles:
      - $values/argocd/zabbix/zabbix_values.yaml
  - repoURL: https://github.com/aeciopires/adsoft.git
    # Branch or tag name
    targetRevision: master
    ref: values
  # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
    - CreateNamespace=true
