services:
  app_crud_api:
    container_name: app_crud_api
    build:
      context: '.'
    image: adsoft/app_crud_api:1.1.0
    environment:
      MONGODB_URI: "mongodb://db:27017/crud-node-mongo-docker"
    ports:
      - "9000:9000"
    depends_on:
      - "db"
    restart: always
  db:
    container_name: db
    image: mongo:8.0
    # Long syntax to declare ports
    # https://docs.docker.com/reference/compose-file/services/#ports
    ports:
      - target: 27017    # container
        published: 27018 # host
        protocol: tcp
    volumes:
      - /docker/adsoft/db_crud_api:/data/db
    restart: always
